# Generated by Django 4.1.3 on 2023-07-01 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Associated_company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_name', models.CharField(max_length=100)),
                ('pr_salt', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('pr_detail', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('pr_instructions', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('pr_type', models.CharField(max_length=55)),
                ('pr_price', models.IntegerField(default=0)),
                ('pr_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Associated_company.company')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
