# Generated by Django 4.1.3 on 2023-07-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_pr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
