# Generated by Django 4.1.3 on 2023-07-26 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_product_pr_name_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('tmp_id', models.AutoField(primary_key=True, serialize=False)),
                ('tmp_name', models.CharField(default=None, max_length=100)),
                ('tmp_description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('status', models.BooleanField(default=True)),
                ('tmp_pr1_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
            options={
                'db_table': 'template',
            },
        ),
    ]
