# Generated by Django 4.1.3 on 2023-07-26 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='tmp_pr1_1',
        ),
        migrations.AddField(
            model_name='templates',
            name='tmp_pr_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_pr1', to='Products.product'),
        ),
        migrations.AddField(
            model_name='templates',
            name='tmp_pr_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_pr2', to='Products.product'),
        ),
    ]
