# Generated by Django 4.1.3 on 2023-07-26 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_remove_templates_tmp_pr1_1_templates_tmp_pr_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='tmp_pr_10',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_pr10', to='Products.product'),
        ),
        migrations.AddField(
            model_name='templates',
            name='tmp_pr_3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_pr3', to='Products.product'),
        ),
        migrations.AddField(
            model_name='templates',
            name='tmp_pr_4',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_pr4', to='Products.product'),
        ),
        migrations.AddField(
            model_name='templates',
            name='tmp_pr_5',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_pr5', to='Products.product'),
        ),
        migrations.AddField(
            model_name='templates',
            name='tmp_pr_6',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_pr6', to='Products.product'),
        ),
        migrations.AddField(
            model_name='templates',
            name='tmp_pr_7',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_pr7', to='Products.product'),
        ),
        migrations.AddField(
            model_name='templates',
            name='tmp_pr_8',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_pr8', to='Products.product'),
        ),
        migrations.AddField(
            model_name='templates',
            name='tmp_pr_9',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_pr9', to='Products.product'),
        ),
    ]
