# Generated by Django 4.1.3 on 2023-06-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cmp_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmp_code', models.CharField(max_length=6, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('ceo_name', models.CharField(max_length=100)),
                ('dealer_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('dealer_address', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('dealer_mobile', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('dealer_whatsapp_mobile', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('company_type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('whatsapp_mobile', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('status', models.IntegerField(default=1)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('added_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
