# Generated by Django 4.1.3 on 2023-07-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0004_alter_branch_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
