# Generated by Django 4.1.3 on 2023-07-12 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farmer', '0002_alter_farmer_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('tns_id', models.AutoField(primary_key=True, serialize=False)),
                ('tns_date', models.DateTimeField(auto_now_add=True)),
                ('fm_mobile', models.CharField(max_length=12)),
                ('product_list', models.CharField(max_length=1000)),
                ('total_transaction', models.IntegerField()),
                ('total_due', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('fm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer.farmer')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
