# Generated by Django 4.1.3 on 2023-07-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='paydown',
            field=models.IntegerField(default=0),
        ),
    ]
