# Generated by Django 4.1.3 on 2023-06-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('fm_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=200)),
                ('gender', models.CharField(default='Male', max_length=6)),
                ('address', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=12)),
                ('whatsapp_mobile', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('image', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('status', models.IntegerField(default=1)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('city_pincode', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('added_by', models.IntegerField(blank=True, default=None, null=True)),
                ('added_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'farmer',
            },
        ),
    ]
