# Generated by Django 4.1.3 on 2023-06-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='mobile',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
